/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Contato: typeof import('./src/components/Contato.vue')['default']
    ConteudoPrincipal: typeof import('./src/components/ConteudoPrincipal.vue')['default']
    Empregos: typeof import('./src/components/Empregos.vue')['default']
    MeusProjetos: typeof import('./src/components/MeusProjetos.vue')['default']
    MinhasSkill: typeof import('./src/components/MinhasSkill.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SobreMim: typeof import('./src/components/SobreMim.vue')['default']
    Teste: typeof import('./src/components/teste.vue')['default']
  }
}
